CREATE TABLE topicos (

    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    mensagem VARCHAR(255) NOT NULL,
    curso VARCHAR(255) NOT NULL,
    data DATETIME NOT NULL,

    PRIMARY KEY(id)
);